### ISSUE TITLE
Feedback on week 10 project progress for CS2113T-W13-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W13-2/main#102]
## Team progress for mid `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-29 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-W13-2/main/issues/92 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/88 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/87 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/86 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/55 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/52 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/49 (:heavy_check_mark: well done!)
* [x] New JAR released on GitHub.(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @claysmilesoil for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/88 (:heavy_check_mark: well done!)
## Individual progress of @glenwong97 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/87 (:heavy_check_mark: well done!)
## Individual progress of @kishore03109 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [ ] Has issues/PRs assigned for `v1.3` milestone (:exclamation: try to do by next milestone)
## Individual progress of @rusdihaizim for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/92 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/86 (:heavy_check_mark: well done!)

Tutor: @flxffy

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-23 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
