### ISSUE TITLE
Feedback on week 12 project progress for CS2113T-W13-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W13-2/main#156]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline 2019-11-12 set(:exclamation: try to do by next milestone)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-W13-2/main/issues/149 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/147 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/145 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/144 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/143 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/142 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/141 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/140 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/139 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/138 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/137 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/136 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/135 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/134 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/133 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/132 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/131 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/130 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/129 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/128 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/127 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/126 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/120 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/56 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/47 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/46 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/39 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/37 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/36 (:heavy_check_mark: well done!)
## Individual progress of @claysmilesoil for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/149 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/140 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/136 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/131 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/127 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @glenwong97 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/147 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/145 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/139 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/135 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/130 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @kishore03109 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/134 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/132 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @rusdihaizim for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W13-2/main/issues/144 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/143 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/142 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/138 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/137 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/133 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/128 https://github.com/AY1920S1-CS2113T-W13-2/main/issues/120 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @flxffy

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-06 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
